In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib_inline

In [7]:
df =  pd.read_csv('Bengaluru_House_Data.CSV')

In [8]:
df1 = pd.DataFrame(df)

In [9]:
df1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [16]:
df2 = df1.drop(['area_type','availability','society','balcony'],axis=1)

In [17]:
df2.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [18]:
df2.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [19]:
df2.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [23]:
df3 = df2.dropna()

In [24]:
df3.isna().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [25]:
df3.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [28]:
df3['size'].unique()

<ArrowStringArray>
[     '2 BHK',  '4 Bedroom',      '3 BHK',      '4 BHK',  '6 Bedroom',
  '3 Bedroom',      '1 BHK',       '1 RK',  '1 Bedroom',  '8 Bedroom',
  '2 Bedroom',  '7 Bedroom',      '5 BHK',      '7 BHK',      '6 BHK',
  '5 Bedroom',     '11 BHK',      '9 BHK',  '9 Bedroom',     '27 BHK',
 '10 Bedroom', '11 Bedroom',     '10 BHK',     '19 BHK',     '16 BHK',
 '43 Bedroom',     '14 BHK',      '8 BHK', '12 Bedroom',     '13 BHK',
 '18 Bedroom']
Length: 31, dtype: str

In [31]:

df3['bhk'] = df3['size'].apply(lambda x :int(x.split(' ')[0]))

In [32]:
df3.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [35]:
df4 = df3.drop(['size'],axis=1)

In [36]:
df4.head()

                   location total_sqft  bath   price  bhk
0  Electronic City Phase II       1056   2.0   39.07    2
1          Chikka Tirupathi       2600   5.0  120.00    4
2               Uttarahalli       1440   2.0   62.00    3
3        Lingadheeranahalli       1521   3.0   95.00    3
4                  Kothanur       1200   2.0   51.00    2

In [37]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [38]:
df4[~df4['total_sqft'].apply(is_float)].head()

               location   total_sqft  bath    price  bhk
30            Yelahanka  2100 - 2850   4.0  186.000    4
122              Hebbal  3067 - 8156   4.0  477.000    4
137  8th Phase JP Nagar  1042 - 1105   2.0   54.005    2
165            Sarjapur  1145 - 1340   2.0   43.490    2
188            KR Puram  1015 - 1540   2.0   56.800    2

In [61]:
def convert(x):
    token = x.split('-')
    if len(token) ==2:
        return (float(token[0])+float(token[1]))/2
    try:
        return float(x)
    except:
        return None

In [62]:
df5 = df4.copy()
df5['total_sqft']= df5['total_sqft'].apply(convert)

In [48]:
df5.head()

                   location  total_sqft  bath   price  bhk
0  Electronic City Phase II      1056.0   2.0   39.07    2
1          Chikka Tirupathi      2600.0   5.0  120.00    4
2               Uttarahalli      1440.0   2.0   62.00    3
3        Lingadheeranahalli      1521.0   3.0   95.00    3
4                  Kothanur      1200.0   2.0   51.00    2

In [49]:
df5.total_sqft.unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ], shape=(1973,))

In [55]:
df5 = df4.copy()

In [65]:
df5['price_per_sqft'] = df5['price']*100000 /df5['total_sqft']

In [64]:
df5.dtypes

location              str
total_sqft        float64
bath              float64
price             float64
bhk                 int64
price_per_sqft    float64
dtype: object

In [76]:
df5.head()

                   location  total_sqft  bath   price  bhk  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07    2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00    4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00    3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00    3     6245.890861
4                  Kothanur      1200.0   2.0   51.00    2     4250.000000

In [77]:
df5['location'].unique()

<ArrowStringArray>
[                       'Electronic City Phase II',
                                'Chikka Tirupathi',
                                     'Uttarahalli',
                              'Lingadheeranahalli',
                                        'Kothanur',
                                      'Whitefield',
                                'Old Airport Road',
                                    'Rajaji Nagar',
                                    'Marathahalli',
                                    'Gandhi Bazar',
 ...
                               'Masjid e Alkareem',
                                   'Sindhi Colony',
                             'Kanakapur main road',
                       'Prasanna layout Herohalli',
                               'Sarvobhogam Nagar',
                                  'Pattegarhpalya',
                                     'Tilak Nagar',
 '12th cross srinivas nagar banshankari 3rd stage',
                               'Havanur extension',
                                   'Abshot Layout']
Length: 1293, dtype: str

In [72]:
location = df5.groupby('location')['location'].count().sort_values(ascending=False)

In [85]:
locationless = location[location<=10]

In [74]:
df5['location'] = df5['location'].apply(lambda x: x.strip())

In [86]:
locationless

location
Nagadevanahalli                                       10
Naganathapura                                         10
BTM 1st Stage                                         10
Nagappa Reddy Layout                                  10
Basapura                                              10
                                                      ..
bsk 6th stage 2ad block near sri conversation hall     1
beml layout, basaveshwara nagar                        1
basaveshwarnagar                                       1
banashankari stage iii sa                              1
asha township, off hennur road                         1
Name: location, Length: 1063, dtype: int64

In [87]:
df5.location.unique()

<ArrowStringArray>
[                       'Electronic City Phase II',
                                'Chikka Tirupathi',
                                     'Uttarahalli',
                              'Lingadheeranahalli',
                                        'Kothanur',
                                      'Whitefield',
                                'Old Airport Road',
                                    'Rajaji Nagar',
                                    'Marathahalli',
                                    'Gandhi Bazar',
 ...
                               'Masjid e Alkareem',
                                   'Sindhi Colony',
                             'Kanakapur main road',
                       'Prasanna layout Herohalli',
                               'Sarvobhogam Nagar',
                                  'Pattegarhpalya',
                                     'Tilak Nagar',
 '12th cross srinivas nagar banshankari 3rd stage',
                               'Havanur extension',
                                   'Abshot Layout']
Length: 1293, dtype: str

In [88]:
df5.location = df5.location.apply(lambda x :'other' if x in locationless else x)

In [91]:
df5.head()

                   location  total_sqft  bath   price  bhk  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07    2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00    4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00    3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00    3     6245.890861
4                  Kothanur      1200.0   2.0   51.00    2     4250.000000

In [93]:
df5.location.unique()

<ArrowStringArray>
['Electronic City Phase II',         'Chikka Tirupathi',
              'Uttarahalli',       'Lingadheeranahalli',
                 'Kothanur',               'Whitefield',
         'Old Airport Road',             'Rajaji Nagar',
             'Marathahalli',                    'other',
 ...
              'Whietfield,', 'Electronic city Phase 1,',
   'HSR Layout 7th sector,',               'Jayanagar,',
            'Haralur Road,',           'Panathur Road,',
 'Electronic city phase 1,',              'Banasawadi,',
         'Kanakapura Road,', 'Electronic City Phase 1,']
Length: 271, dtype: str

In [97]:
df6 = df5[~(df5.total_sqft/df5.bhk<300)]

In [98]:
df6

                       location  total_sqft  bath   price  bhk  price_per_sqft
0      Electronic City Phase II      1056.0   2.0   39.07    2     3699.810606
1              Chikka Tirupathi      2600.0   5.0  120.00    4     4615.384615
2                   Uttarahalli      1440.0   2.0   62.00    3     4305.555556
3            Lingadheeranahalli      1521.0   3.0   95.00    3     6245.890861
4                      Kothanur      1200.0   2.0   51.00    2     4250.000000
...                         ...         ...   ...     ...  ...             ...
13315                Whitefield      3453.0   4.0  231.00    5     6689.834926
13316                     other      3600.0   5.0  400.00    4    11111.111111
13317     Raja Rajeshwari Nagar      1141.0   2.0   60.00    2     5258.545136
13318           Padmanabhanagar      4689.0   4.0  488.00    4    10407.336319
13319              Doddathoguru       550.0   1.0   17.00    1     3090.909091

[12502 rows x 6 columns]

In [99]:
df6.price_per_sqft.describe()

count     12456.000000
mean       6308.502826
std        4168.127339
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [102]:
def remove_outs(df):
    df_out = pd.DataFrame()
    for key , subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf [(subdf.price_per_sqft >(m-st)) & (subdf.price_per_sqft <=(m+st))]
        df_out = pd.concat([df_out,reduced_df],ignore_index=True)
    return df_out

In [104]:
df7 = remove_outs(df6)

In [105]:
df7.describe()

         total_sqft          bath        price           bhk  price_per_sqft
count  10210.000000  10210.000000  10210.00000  10210.000000    10210.000000
mean    1502.887238      2.473262     90.95350      2.571596     5659.837177
std      876.668748      0.981522     86.20678      0.896121     2273.769545
min      300.000000      1.000000     10.00000      1.000000     1250.000000
25%     1108.000000      2.000000     49.00000      2.000000     4242.057674
50%     1280.000000      2.000000     67.00000      2.000000     5174.219497
75%     1650.000000      3.000000    100.00000      3.000000     6425.272826
max    30400.000000     16.000000   2200.00000     16.000000    24509.803922

In [106]:
df8 = df7.drop(['price_per_sqft'],axis=1)

In [109]:
df8.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [113]:
dummy = pd.get_dummies(df8.location)

In [121]:
df9 = pd.concat([df8,dummy.drop('other',axis=1)],axis=1)

In [122]:
df9.head()

,location,total_sqft,bath,price,bhk,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,...,Vishwapriya Layout,Vittasandra,Whitefield,"Whitefield,",Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,south
0,1st Block Jayanagar,2850.0,4.0,428.0,4,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1st Block Jayanagar,1630.0,3.0,194.0,3,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1st Block Jayanagar,1875.0,2.0,235.0,3,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1st Block Jayanagar,1200.0,2.0,130.0,3,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1st Block Jayanagar,1235.0,2.0,148.0,2,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [123]:
df10 = df9.drop(['location'],axis=1)

In [124]:
df10.head()

,total_sqft,bath,price,bhk,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,...,Vishwapriya Layout,Vittasandra,Whitefield,"Whitefield,",Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,south
0,2850.0,4.0,428.0,4,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1630.0,3.0,194.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1875.0,2.0,235.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1200.0,2.0,130.0,3,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1235.0,2.0,148.0,2,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [125]:
x = df10.drop(['price'],axis=1)

In [126]:
x.head()

,total_sqft,bath,bhk,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,...,Vishwapriya Layout,Vittasandra,Whitefield,"Whitefield,",Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,south
0,2850.0,4.0,4,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1630.0,3.0,3,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1875.0,2.0,3,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1200.0,2.0,3,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1235.0,2.0,2,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [127]:
y = df10.price

In [129]:
y.head()

0    428.0
1    194.0
2    235.0
3    130.0
4    148.0
Name: price, dtype: float64

In [130]:
from sklearn.model_selection import train_test_split

In [131]:
x_train,x_tests,y_train,y_tests = train_test_split(x,y,test_size=0.2)

In [132]:
from sklearn.linear_model import LinearRegression

In [133]:
model = LinearRegression()

In [134]:
model.fit(x_train,y_train)

LinearRegression()

In [136]:
model.score(x_tests,y_tests)

0.8240255568607311

In [138]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

In [139]:
cv = ShuffleSplit(n_splits=5,test_size=0.2,random_state=0)

In [140]:
cross_val_score(LinearRegression(),x,y,cv=cv)

array([0.80463869, 0.79026801, 0.76004638, 0.85385805, 0.81121025])

In [145]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso

In [142]:
from sklearn.tree import DecisionTreeRegressor

In [178]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor


def select_models(x, y):
    algos = {
        'LinearRegression': {
            'model': LinearRegression(),
            'params': {
                'fit_intercept': [True, False]
            }
        },
        'DecisionTreeRegressor': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion': ['squared_error', 'friedman_mse'],
                'splitter': ['best', 'random']
            }
        },
        'Lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1.0, 2.0],
                'selection': ['random', 'cyclic']
            }
        }
    }

    results = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

    for name, info in algos.items():
        model = info['model']
        param_grid = info['params']
        grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=cv)
        grid.fit(x, y)
        results.append({
            'model_name': name,
            'best_score': grid.best_score_,
            'best_params': grid.best_params_,
            'best_estimator': grid.best_estimator_
        })

    return pd.DataFrame(results)

In [179]:
p = select_models(x,y)

In [180]:
p

,model_name,best_score,best_params,best_estimator
0,LinearRegression,0.804004,{'fit_intercept': True},LinearRegression()
1,DecisionTreeRegressor,0.693739,"{'criterion': 'friedman_mse', 'splitter': 'ran...",DecisionTreeRegressor(criterion='friedman_mse'...
2,Lasso,0.685751,"{'alpha': 1.0, 'selection': 'random'}",Lasso(selection='random')

In [181]:
import pickle

In [182]:
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [184]:
import json

In [185]:
colums = {
    'data_columns': [col.lower() for col in x.columns]
}

In [186]:
with open('model.json', 'w') as f:
    f.write(json.dumps(colums))

In [194]:
location = '1st Block Jayanagar'
input_data = {col: 0 for col in x.columns}
input_data['total_sqft'] = 2850.0
input_data['bath'] = 4.0
input_data['bhk'] = 4
input_data[location if location in input_data else 'other'] = 1

model.predict(pd.DataFrame(['1st Block Jayanagar', 2850.0, 4.0, 4]))

c:\Users\offic\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: could not convert string to float: '1st Block Jayanagar'

AttributeError: 'DataFrame' object has no attribute 'disc'